ISfTE/Controllers/AbstractReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ISfTE.DataAccess.Data.Repository.IRepository;
using ISfTE.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ISfTE.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class AbstractReviewController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public AbstractReviewController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Get()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var abstracts = _unitOfWork.Abstract.GetAll(a => a.AuthorId != claim.Value, null, "ApplicationUser");

                return Json(new
                {
                    data = from a in abstracts
                           select new
                           {
                               Id = a.Id,
                               Title = a.Title,
                               Author = a.ApplicationUser.FullName,
                               DocPath = a.DocPath,
                               Approved = a.Approved,
                               Date = a.ReviewDate,
                               RateCount = _unitOfWork.AbstractRating.RatingCount(a.Id),
                               Rating = _unitOfWork.AbstractRating.AvgRating(a.Id)
                           }
                });
            }

            return NotFound();
        }
    }
}

ISfTE/Pages/AbstractRating/Upsert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ISfTE.DataAccess.Data.Repository.IRepository;
using ISfTE.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ISfTE.Pages.AbstractRating
{
    public class UpsertModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public UpsertModel(IUnitOfWork unitOfWork, IWebHostEnvironment hostingEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostingEnvironment = hostingEnvironment;
        }

        [BindProperty]
        public AbstractRatingVM AbstractRatingObj { get; set; }

        public IActionResult OnGet(int? ratingId, int? abstractId)
        {
            //check to see if the abstract has been rated before by the user
            AbstractRatingObj = new AbstractRatingVM();
            if(ratingId != null)
            {
                AbstractRatingObj.AbstractRating = _unitOfWork.AbstractRating.GetFirstOrDefault(a => a.Id == ratingId);
            }
            else
            {
                //if not, initialize the rating VM
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                AbstractRatingObj.AbstractRating = new Models.AbstractRating
                {
                    Id = 0,
                    AbstractId = (int)abstractId,
                    RaterId = claim.Value,
                    ConferenceFit = 3,
                    Contribution = 3,
                    Mechanics = 3
                };
            }
            AbstractRatingObj.Abstract = _unitOfWork.Abstract.GetFirstOrDefault(a => a.Id == abstractId, "ApplicationUser");

            if (AbstractRatingObj.AbstractRating == null || AbstractRatingObj.Abstract == null)
            {
                return NotFound();
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //save the rating to the db
            AbstractRatingObj.AbstractRating.RatingDate = DateTime.Now;
            if (AbstractRatingObj.AbstractRating.Id == 0)
            {
                _unitOfWork.AbstractRating.Add(AbstractRatingObj.AbstractRating);
            }
            else
            {
                _unitOfWork.AbstractRating.Update(AbstractRatingObj.AbstractRating);
            }

            _unitOfWork.Save();

            return RedirectToPage("./Index");
        }
    }
}

ISfTE/Pages/AbstractReview/Upsert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ISfTE.DataAccess.Data.Repository.IRepository;
using ISfTE.Models.ViewModels;
using ISfTE.Utility;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ISfTE.Pages.AbstractReview
{
    public class UpsertModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnvironment;
        

        public UpsertModel(IUnitOfWork unitOfWork, IWebHostEnvironment hostingEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostingEnvironment = hostingEnvironment;
            
        }

        [BindProperty]
        public AbstractReviewVM abstractObj { get; set; }

        public void OnGet(int id)
        {
            //populate the VM
            abstractObj = new AbstractReviewVM
            {
                Abstract = _unitOfWork.Abstract.GetFirstOrDefault(a => a.Id == id, "ApplicationUser"),
                AbstractRatings = _unitOfWork.AbstractRating.GetAll(r => r.AbstractId == id, null, "ApplicationUser")
            };
        }

        public IActionResult OnPostApprove()
        {
            //if approved, update the abstract and the current user status to reflect the change
            var objFromDb = _unitOfWork.Abstract.GetFirstOrDefault(a => a.Id == abstractObj.Abstract.Id, "ApplicationUser");
            abstractObj.Abstract = objFromDb;

            abstractObj.Abstract.Approved = true;
            abstractObj.Abstract.ReviewDate = DateTime.Now;

            _unitOfWork.Abstract.Update(abstractObj.Abstract);
            if (abstractObj.Abstract.ApplicationUser.Status != SD.Admin && abstractObj.Abstract.ApplicationUser.Status != SD.Rater)
            {
                
                _unitOfWork.ApplicationUser.UpdateRole(abstractObj.Abstract.AuthorId, SD.AbstractApproved);

            }
            _unitOfWork.Save();

            return RedirectToPage("Index");
        }

        public IActionResult OnPostReject()
        {
            //if rejectedc, update the abstract and the current user status to reflect the change
            var objFromDb = _unitOfWork.Abstract.GetFirstOrDefault(a => a.Id == abstractObj.Abstract.Id, "ApplicationUser");
            abstractObj.Abstract = objFromDb;

            abstractObj.Abstract.Approved = false;
            abstractObj.Abstract.ReviewDate = DateTime.Now;

            _unitOfWork.Abstract.Update(abstractObj.Abstract);
            if(abstractObj.Abstract.ApplicationUser.Status != SD.Admin && abstractObj.Abstract.ApplicationUser.Status != SD.Rater)
            {
                
                _unitOfWork.ApplicationUser.UpdateRole(abstractObj.Abstract.AuthorId, SD.AbstractRejected);

            }
            _unitOfWork.Save();

            return RedirectToPage("Index");
        }
    }
}

ISfTE/Pages/Admin/Country/Upsert.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ISfTE.DataAccess.Data.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ISfTE.Models.ViewModels;

namespace ISfTE.Pages.Admin.Country
{
    public class UpsertModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public UpsertModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [BindProperty]
        public CountryVM CountryObj { get; set; }
        public IActionResult OnGet(int? id)
        {

            CountryObj = new CountryVM
            {
                CountryTypeList =
                _unitOfWork.CountryType.GetCountryTypeListForDropDown(),

                Country = new Models.Country()
            };

            if (id != null) //edit
            {
                CountryObj.Country = _unitOfWork.Country.GetFirstOrDefault(u => u.Id == id);
                if (CountryObj == null)
                {
                    return NotFound();
                }
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (CountryObj.Country.Id == 0) //new country
            {
                _unitOfWork.Country.Add(CountryObj.Country);
            }

            else //edit
            {
                _unitOfWork.Country.Update(CountryObj.Country);
            }

            _unitOfWork.Save();
            return RedirectToPage("./Index");
        }
    }
}

ISfTE/Pages/AbstractReview/Index.cshtml
@page
@using ISfTE.Utility

@if (User.IsInRole(SD.AdminRole))
{
    <div class="border backgroundWhite container">
        <div class="row">
            <div class="col-6">
                <h2 class="text-info">Abstract Review</h2>
            </div>
        </div>
        <br />
        <br />
        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Ratings</th>
                    <th>Avg Rating</th>
                    <th>Approval</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
}
else
{
    <h1 class="text-danger">Access Denied</h1>
}


@section Scripts{
    <script src="~/js/abstractReview.js"></script>

}

ISfTE/Pages/AbstractReview/Upsert.cshtml
@page
@model ISfTE.Pages.AbstractReview.UpsertModel
@using ISfTE.Utility
@{
    ViewData["Title"] = "Upsert";
}

@if (User.IsInRole(SD.AdminRole))
{
    <h2 class="text-info">Abstract Approval</h2>
    <hr />
    <div class="row col-12 align-items-center">
        <div class="col-8">
            <h2>@Model.abstractObj.Abstract.Title</h2>
            <h3><i>Submitted by </i>@Model.abstractObj.Abstract.ApplicationUser.FullName</h3>
            <h4><i>From </i> @Model.abstractObj.Abstract.ApplicationUser.Institution</h4>
        </div>
        <div class="col-4">
            <h3><a class="btn btn-primary col-12" href="@Model.abstractObj.Abstract.DocPath" target="_blank">View Here</a></h3>
        </div>

        <hr />
    </div>

    <div style="padding-left:50px; padding-right:50px; padding-top:25px; padding-bottom:25px;">
        @foreach (var rating in Model.abstractObj.AbstractRatings)
        {
            <div class="container">
                <div class="row bg-info text-white col-12">
                    <div class="col-8">
                        <h5>@rating.ApplicationUser.FullName</h5>
                        <h6>Email: @rating.ApplicationUser.Email</h6>
                        <h6>Phone: @rating.ApplicationUser.PhoneNumber</h6>
                    </div>
                    <div class="col-4 align-items-center text-right">
                        <h5>@rating.RatingDate.ToString("d")</h5>
                    </div>

                </div>
                <div class="row col-12 border" style="padding-top:5px; padding-bottom:5px;">
                    <div class="col-3 border-right border-bottom">
                        <h5>Ratings</h5>
                    </div>
                    <div class="col-9 border-bottom">
                        <h5>Reviewer Comments</h5>
                    </div>
                    <div class="col-3 border-right">
                        <br />
                        <h6>Conference Fit: @rating.ConferenceFit</h6>
                        <h6>Contribution: @rating.Contribution</h6>
                        <h6>Mechanics: @rating.Mechanics</h6>
                        <br />
                        <h6 style="color:red;">Average: @rating.AvgRating</h6>
                    </div>
                    <div class="col-9">
                        <textarea readonly id="txtDesc" style="width:100%; height:100%;">@rating.Comments</textarea>
                    </div>
                </div>
            </div>
            <hr class="c" />
        }

        @if (Model.abstractObj.AbstractRatings.Count() == 0)
        {
            <div class="text-center">
                <h3 class="text-danger">No Ratings Submitted</h3>
            </div>

        }
    </div>
    <div class="justify-content-center">


        <form method="post">
            <div class="col-12 d-flex justify-content-around">
                <input type="hidden" asp-for="@Model.abstractObj.Abstract.Id" value="@Model.abstractObj.Abstract.Id" />

                <button type="submit" class="col-4 btn btn-success" asp-page-handler="approve">APPROVE</button>
                <button type="submit" class="col-4 btn btn-danger" asp-page-handler="reject">REJECT</button>

                <a class="col-2 text-white btn btn-primary" asp-page="Index">Back to List</a>
            </div>

        </form>

    </div>
}
else
{
    <h1 class="text-danger">Access Denied</h1>
}
@section Scripts {
    <script>
        tinymce.init(
            {
                selector: 'textarea',
                plugins: 'lists',
                menubar: false,
                statusbar: false,
                readonly: 1
            });
    </script>
}